skills:
  mining:
    color: CYAN
    xp-per-level: 100
  foraging:
    color: DARK_GREEN
    xp-per-level: 100
  farming:
    color: LIME
    xp-per-level: 100
  combat:
      color: RED
      xp-per-level: 100
  brewing:
    color: GOLD
    xp-per-level: 100
  enchanting:
    color: DARK_AQUA
    xp-per-level: 100