name: SkillCraft
version: 1.0.0
main: com.SkillCraft.GitHub.MainPlugin
api-version: '1.21'
author: FelipeSpiderman
description: A simple skills plugin for Paper.
commands:
  skills:
    description: Opens the skills GUI.
    usage: /skills